version: '3'

services:
  restapi:
    #volumes:
    #  - ./yt2spec/:/usr/local/src/yt2spec/
    build:
      context: ./yt2spec
      dockerfile: Dockerfile
    command: >
      python3 ./flask_rest.py
    ports:
      - 6060:6060